name: Deployment main

on:
  push:
    branches:
      - develop
    paths:
      - "service/main/**"
      - "packages/**"
    

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read

    env:
      SERVICE_NAME: main
      
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Deploy to xquare
        uses: team-xquare/xquare-deployment-action@master
        with:
          environment: stag
          access_key: ${{ secrets.MAIN_ACCESS_KEY }}
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base_url: service/${{ env.SERVICE_NAME }}
          config_file_path: service/${{ env.SERVICE_NAME }}/.xquare/config.yaml
          yarn_docker_build: true
          yarn_workspace: "@service/${{ env.SERVICE_NAME }}"
