name: Discord Notification
on:
  pull_request:
    branches: [ "main", "develop" ]
jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: sarisia/actions-status-discord@v1
      with:
        title: 🔀 Pull Request 🔀
        description: "**Who ate the Nutella?**"
        content: "<@&1154312086965465119>"
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        color: 000000
        image: ${{ secrets.IMAGE_URL }}
